### ISSUE TITLE
REMOVEHEADER turns output into 'undefined'

### ISSUE THREAD

**Issue by dol** [zalando/bigbash#11]
When translating the following SQL statement the translated bash output on http://bigbash.it/ is 'undefined'.

```
CREATE TABLE foo (bar TEXT)

MAP foo TO 'do something'
    DELIMITER ',' QUOTE '"' TYPE 'RAW' REMOVEHEADER;
```

**Comment by Borisvl** [comment]
'Removeheader' is not supported for RAW input, it now returns a proper error.
To remove a header line in RAW input manually, pipe the output through 'tail -n+2'.
